export interface Count1025NextHTTPSPokeapiCoAPIV2PokemonSpeciesOffset20Limit20PreviousNullResultsNameBulbasaurURLHTTPSPokeapiCoAPIV2PokemonSpecies1NameIvysaurURLHTTPSPokeapiCoAPIV2PokemonSpecies2NameVenusaurURLHTTPSPokeapiCoAPIV2PokemonSpecies3NameCharmanderURLHTTPSPokeapiCoAPIV2PokemonSpecies4NameCharmeleonURLHTTPSPokeapiCoAPIV2PokemonSpecies5NameCharizardURLHTTPSPokeapiCoAPIV2PokemonSpecies6NameSquirtleURLHTTPSPokeapiCoAPIV2PokemonSpecies7NameWartortleURLHTTPSPokeapiCoAPIV2PokemonSpecies8NameBlastoiseURLHTTPSPokeapiCoAPIV2PokemonSpecies9NameCaterpieURLHTTPSPokeapiCoAPIV2PokemonSpecies10NameMetapodURLHTTPSPokeapiCoAPIV2PokemonSpecies11NameButterfreeURLHTTPSPokeapiCoAPIV2PokemonSpecies12NameWeedleURLHTTPSPokeapiCoAPIV2PokemonSpecies13NameKakunaURLHTTPSPokeapiCoAPIV2PokemonSpecies14NameBeedrillURLHTTPSPokeapiCoAPIV2PokemonSpecies15NamePidgeyURLHTTPSPokeapiCoAPIV2PokemonSpecies16NamePidgeottoURLHTTPSPokeapiCoAPIV2PokemonSpecies17NamePidgeotURLHTTPSPokeapiCoAPIV2PokemonSpecies18NameRattataURLHTTPSPokeapiCoAPIV2PokemonSpecies19NameRaticateURLHTTPSPokeapiCoAPIV2PokemonSpecies20 {
    count:    number;
    next:     string;
    previous: null;
    results:  Result[];
}

export interface Result {
    name: string;
    url:  string;
}
